services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    entrypoint: >
      sh -c "
      if ! id -u adminer > /dev/null 2>&1; then
        echo 'adminer:x:999:999::/home/adminer:/bin/sh' >> /etc/passwd;
      fi;
      exec docker-php-entrypoint"
      
  nextjs:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=$(DATABASE_URL)
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run dev
