version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - app-network
        command: sh -c "while ! nc -z db 5432; do sleep 1; done && npx prisma migrate dev && npm run dev"

    db:
        image: postgres:15
        env_file:
            - .env
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - app-network

volumes:
    postgres-data:

networks:
    app-network:
        driver: bridge
